<a href="https://colab.research.google.com/github/iLikeKatz/LotteryWinningTest/blob/main/PytorchFullCourse/Tensor/CreateAnyTensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

### Random value

In [3]:
#a random  tensor of shape
tens = torch.rand(1, 2, 3) #shape 1, 2, 3 with random values
tens

tensor([[[0.9588, 0.6943, 0.6052],
         [0.2440, 0.2459, 0.2457]]])

In [4]:
#a random tensor with similar shape to an image tensor
ImageTens = torch.rand(size=(224, 224, 3))
ImageTens.shape, ImageTens.ndim


(torch.Size([224, 224, 3]), 3)

### Ones and Zeros

In [5]:
#create a tensor with all zero values
zeroTens = torch.zeros(3,2)
zeroTens

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [6]:
#create a tensor with all one values
oneTens = torch.ones(3,2)
oneTens

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

### Creating a range of tensors and tensors-like

In [7]:
#arange
arange = torch.arange(1, 10,) #meaning a tensor that has values from 1  to 9 (10 - 1) and also we can define the step
arange

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#tensors-like
example  = torch.arange(1, 11)
ten_zeros = torch.zeros_like(example) #0 replaces whole example
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TensorsDtype

In [20]:
#in torch we most used float32 or 16, device "cpu" or "cuda" if u have nividia gpu, requires_grad force to set True if for deep learning ()
tens = torch.tensor(1, device=None,
                                dtype=torch.float32,
                                 requires_grad=True )
tens

tensor(1., requires_grad=True)

In [36]:
#change dtypes
ten16 = torch.tensor(1, dtype=torch.float16)
reDtype32 = ten16.type(torch.float32)
reDtype32.dtype, ten16.dtype

(torch.float32, torch.float16)