<a href="https://colab.research.google.com/github/iLikeKatz/LotteryWinningTest/blob/main/PytorchFullCourse/Tensor/MatrixMultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import  torch

### Element- Wise
this is simple such as
 2 * [1, 2, 3] then [2,4,6] cuz the whole tensor multiplied by 2

In [80]:
tens = torch.tensor([1,2,3])
tens * 2

tensor([2, 4, 6])

In [90]:
# or just
tens * tens #result : 1, 4, 9
#1*1, 2*2, 3*3, i know you can simply understand this, then

tensor([1, 4, 9])

### Dot-Product

>



In [94]:
torch.matmul(tens, tens) #result : 14 f

tensor(14)

### why 14?

In [83]:
#Dot  product by hands
1*1 + 2*2 + 3*3 #this is the processing

14

In [96]:
#another example here
# if it's not 1d, then you have to convert  those two be like, if matrix a's shape = x * y  then b must be y * z
tens1 = torch.tensor([[1,2,3], [4,5,6]])
tens2 = torch.tensor([[7,8], [9,10], [11, 12]])
torch.matmul(tens1, tens2)

tensor([[ 58,  64],
        [139, 154]])

In [85]:
#another way (laziest way and also can confuse you or others)
tens1 @ tens2

tensor([[ 58,  64],
        [139, 154]])

### if matrix  `a = x * y ` and  ` b = y * z`then a @ b will be shape = [x, z]



In [86]:
randomTens = torch.rand(3, 3)
randomTens2 = torch.rand(3,10)
(randomTens @ randomTens2).shape

torch.Size([3, 10])

### TRANSPOSE

In [87]:
#for example
Tensor = torch.rand(2, 3)
Tensor.shape # 2, 3
Tensor.T.shape #3, 2
#after using Transpose it will switches rows and columns

torch.Size([3, 2])